name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like Auto Claude to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Auto Claude would this affect?
      options:
        - Python Backend (auto-claude/)
        - Electron UI (auto-claude-ui/)
        - Both
        - New component
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important for my workflow
        - Critical / Blocking my use

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this?
      options:
        - label: I'm willing to submit a PR for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
